# Generated by Django 3.0.3 on 2020-11-14 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 14, 18, 11, 55, 788445)),
        ),
    ]
